name = "roll-doradobet-pl"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradobet.pl"
HMAC_KEY = "118f7624e521fdc63dc3e557f2f96bb8d6ff0d45dcf8b2173b4a0a0d1827ed06"
COOKIE_NAME = "p2m"
PLAY_PATH = "join-now"
BUTTON_ID = "p851b5685b790f7bd57c1d09ac152e893"
GATE_SALT = "f377198997956423"
